import sys
import unittest
from unittest import mock
from more_itertools import peekable
from lib.jack_token import Keyword, Symbol, Identifier, IntegerConstant, StringConstant
from lib.compilation_engine import CompilationEngine


class TestCompilationEngine(unittest.TestCase):
    def test_compile_statments(self):
        mock_tokens = peekable(
            iter(
                [
                    Keyword("if"),
                    Symbol("("),
                    Identifier("x"),
                    Symbol("<"),
                    IntegerConstant("153"),
                    Symbol(")"),
                    Symbol("{"),
                    Keyword("let"),
                    Identifier("city"),
                    Symbol("="),
                    StringConstant("Paris"),
                    Symbol(";"),
                    Symbol("}"),
                ]
            )
        )
        mock_output_file = mock.Mock()
        CompilationEngine.compile_statements(mock_tokens, mock_output_file)
        mock_output_file.assert_has_calls(
            [
                mock.call.write(Keyword("if").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(Symbol("(").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(Identifier("x").to_xml(3)),
                mock.call.write("\n"),
                mock.call.write(Symbol("<").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(IntegerConstant("153").to_xml(3)),
                mock.call.write("\n"),
                mock.call.write(Symbol(")").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(Symbol("{").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(Keyword("let").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(Identifier("city").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(Symbol("=").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(StringConstant("Paris").to_xml(4)),
                mock.call.write("\n"),
                mock.call.write(Symbol(";").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(Symbol("}").to_xml(1)),
                mock.call.write("\n"),
            ]
        )

    def test_compile_class(self):
        mock_tokens = peekable(
            iter(
                [
                    (Keyword("class"), next(file_without_comments)),
                    (Identifier("Main"), next(file_without_comments)),
                    (Symbol("{"), next(file_without_comments)),
                    (Keyword("static"), next(file_without_comments)),
                    (Keyword("boolean"), next(file_without_comments)),
                    (Identifier("test"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("function"), next(file_without_comments)),
                    (Keyword("void"), next(file_without_comments)),
                    (Identifier("main"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol("{"), next(file_without_comments)),
                    (Keyword("var"), next(file_without_comments)),
                    (Identifier("SquareGame"), next(file_without_comments)),
                    (Identifier("game"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("game"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Identifier("SquareGame"), next(file_without_comments)),
                    (Symbol("."), next(file_without_comments)),
                    (Identifier("new"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("do"), next(file_without_comments)),
                    (Identifier("game"), next(file_without_comments)),
                    (Symbol("."), next(file_without_comments)),
                    (Identifier("run"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("do"), next(file_without_comments)),
                    (Identifier("game"), next(file_without_comments)),
                    (Symbol("."), next(file_without_comments)),
                    (Identifier("dispose"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("return"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Symbol("}"), next(file_without_comments)),
                    (Keyword("function"), next(file_without_comments)),
                    (Keyword("void"), next(file_without_comments)),
                    (Identifier("test"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol("{"), next(file_without_comments)),
                    (Keyword("var"), next(file_without_comments)),
                    (Keyword("int"), next(file_without_comments)),
                    (Identifier("i"), next(file_without_comments)),
                    (Symbol(","), next(file_without_comments)),
                    (Identifier("j"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("var"), next(file_without_comments)),
                    (Identifier("String"), next(file_without_comments)),
                    (Identifier("s"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("var"), next(file_without_comments)),
                    (Identifier("Array"), next(file_without_comments)),
                    (Identifier("a"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("if"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Keyword("false"), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol("{"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("s"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (StringConstant("string constant"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("s"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Keyword("null"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("a"), next(file_without_comments)),
                    (Symbol("["), next(file_without_comments)),
                    (IntegerConstant("1"), next(file_without_comments)),
                    (Symbol("]"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Identifier("a"), next(file_without_comments)),
                    (Symbol("["), next(file_without_comments)),
                    (IntegerConstant("2"), next(file_without_comments)),
                    (Symbol("]"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Symbol("}"), next(file_without_comments)),
                    (Keyword("else"), next(file_without_comments)),
                    (Symbol("{"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("i"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Identifier("i"), next(file_without_comments)),
                    (Symbol("*"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol("-"), next(file_without_comments)),
                    (Identifier("j"), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("j"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Identifier("j"), next(file_without_comments)),
                    (Symbol("/"), next(file_without_comments)),
                    (Symbol("("), next(file_without_comments)),
                    (Symbol("-"), next(file_without_comments)),
                    (IntegerConstant("2"), next(file_without_comments)),
                    (Symbol(")"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Keyword("let"), next(file_without_comments)),
                    (Identifier("i"), next(file_without_comments)),
                    (Symbol("="), next(file_without_comments)),
                    (Identifier("i"), next(file_without_comments)),
                    (Symbol("|"), next(file_without_comments)),
                    (Identifier("j"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Symbol("}"), next(file_without_comments)),
                    (Keyword("return"), next(file_without_comments)),
                    (Symbol(";"), next(file_without_comments)),
                    (Symbol("}"), next(file_without_comments)),
                    (Symbol("}"), next(file_without_comments)),
                ]
            )
        )

        mock_output_file = mock.Mock()
        CompilationEngine.compile_statements(mock_tokens, mock_output_file)
        mock_output_file.assert_has_calls(
            [
                mock.call.write(Keyword("class").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(Identifier("Main").to_xml(3)),
                mock.call.write("\n"),
                mock.call.write(Symbol("{").to_xml(2)),
                mock.call.write("\n"),
                mock.call.write(Keyword("static").to_xml(1)),
                mock.call.write("\n"),
                mock.call.write(StringConstant("Paris").to_xml(4)),
            ]
        )
